FIND_PATH(
	GLFW_INCLUDE_DIRS
	NAMES GLFW/glfw3.h
	PATHS /usr/local/include/
)

FIND_LIBRARY(
	GLFW_LIBRARIES
	NAMES glfw3
	PATHS /usr/local/lib/
)

IF (GLFW_INCLUDE_DIRS AND GLFW_LIBRARIES)
    SET(GLFW_FOUND TRUE)
ENDIF (GLFW_INCLUDE_DIRS AND GLFW_LIBRARIES)

IF (GLFW_FOUND)
    IF (NOT GLFW_FIND_QUIETLY)
        MESSAGE(STATUS "Found GLFW library: ${GLFW_LIBRARIES}")
    ENDIF (NOT GLFW_FIND_QUIETLY)
ELSE (GLFW_FOUND)
    IF (GLFW_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find GLFW library")
    ENDIF (GLFW_FIND_REQUIRED)
ENDIF (GLFW_FOUND)
