FIND_PATH(
	ANTTWEAKBAR_INCLUDE_DIRS
	NAMES AntTweakBar.h
	PATHS /usr/local/include/
)

FIND_LIBRARY(
	ANTTWEAKBAR_LIBRARY
	NAMES AntTweakBar
	PATHS /usr/local/lib/
)

IF (ANTTWEAKBAR_INCLUDE_DIRS AND ANTTWEAKBAR_LIBRARY)
    SET(ANTTWEAKBAR_FOUND TRUE)
ENDIF (ANTTWEAKBAR_INCLUDE_DIRS AND ANTTWEAKBAR_LIBRARY)
