MACRO(MAKE_SAMPLE TRGTNAME)
	ADD_EXECUTABLE(${TRGTNAME} ${TRGTNAME}.cpp ${SRC_FILES} ${HEADER_FILES} ${SHADER_FILES})

	TARGET_LINK_LIBRARIES(${TRGTNAME} glew ${GLFW_LIBRARIES} ${assimp_LIBRARIES})

	IF (WIN32)
		TARGET_LINK_LIBRARIES(${TRGTNAME} opengl32)
	ELSE (WIN32)
		TARGET_LINK_LIBRARIES(${TRGTNAME} GL)		
	ENDIF (WIN32)

	INSTALL(TARGETS ${TRGTNAME} RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX})
ENDMACRO(MAKE_SAMPLE TRGTNAME)

MACRO(MAKE_TASK TRGTNAME)
	ADD_EXECUTABLE(${TRGTNAME} ${SRC_FILES} ${HEADER_FILES})

	TARGET_LINK_LIBRARIES(${TRGTNAME} glew ${GLFW_LIBRARIES} ${assimp_LIBRARIES})

	IF (WIN32)
		TARGET_LINK_LIBRARIES(${TRGTNAME} opengl32)
	ELSE (WIN32)
		TARGET_LINK_LIBRARIES(${TRGTNAME} ${OPENGL_LIBRARIES} ${X11_Xxf86vm_LIB} ${X11_X11_LIB} ${X11_Xrandr_LIB} ${CMAKE_THREAD_LIBS_INIT})
	ENDIF (WIN32)

	INSTALL(TARGETS ${TRGTNAME} RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX})
ENDMACRO(MAKE_TASK TRGTNAME)
