MACRO(MAKE_SAMPLE TRGTNAME)
	ADD_EXECUTABLE(${TRGTNAME} ${TRGTNAME}.cpp ${SRC_FILES} ${HEADER_FILES} ${SHADER_FILES})

	TARGET_LINK_LIBRARIES(${TRGTNAME} glew ${GLFW_LIBRARIES})

	IF (WIN32)
		TARGET_LINK_LIBRARIES(${TRGTNAME} opengl32)
	ELSE (WIN32)
		TARGET_LINK_LIBRARIES(${TRGTNAME} GL)		
	ENDIF (WIN32)

	INSTALL(TARGETS ${TRGTNAME} RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX})
ENDMACRO(MAKE_SAMPLE TRGTNAME)
