macro(MAKE_SAMPLE TRGTNAME)
	add_executable(${TRGTNAME} ${TRGTNAME}.cpp ${SRC_FILES} ${HEADER_FILES} ${SHADER_FILES})

	target_link_libraries(${TRGTNAME} GLEW::glew_s glimg glm glfw ASSIMP::assimp ${ANTTWEAKBAR_LIBRARY})

	if (WIN32)
		#TARGET_LINK_LIBRARIES(${TRGTNAME} opengl32)
	else (WIN32)
		#TARGET_LINK_LIBRARIES(${TRGTNAME} ${OPENGL_LIBRARIES} ${X11_Xxf86vm_LIB} ${X11_Xi_LIB} ${X11_X11_LIB} ${X11_Xrandr_LIB} ${X11_Xcursor_LIB} ${X11_Xinerama_LIB} ${CMAKE_THREAD_LIBS_INIT})
	endif (WIN32)

	install(TARGETS ${TRGTNAME} RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX})
endmacro(MAKE_SAMPLE TRGTNAME)

macro(MAKE_TASK TRGTNAME)
	add_executable(${TRGTNAME} ${SRC_FILES} ${HEADER_FILES})

	target_link_libraries(${TRGTNAME} GLEW::glew_s glimg glm glfw ASSIMP::assimp ${ANTTWEAKBAR_LIBRARY})

	if (WIN32)
		#TARGET_LINK_LIBRARIES(${TRGTNAME} opengl32)
	else (WIN32)		
		#TARGET_LINK_LIBRARIES(${TRGTNAME} ${OPENGL_LIBRARIES} ${X11_Xxf86vm_LIB} ${X11_Xi_LIB} ${X11_X11_LIB} ${X11_Xrandr_LIB} ${X11_Xcursor_LIB} ${X11_Xinerama_LIB} ${CMAKE_THREAD_LIBS_INIT})
	endif (WIN32)

	install(TARGETS ${TRGTNAME} RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX})
endmacro(MAKE_TASK TRGTNAME)
